server:
  port: 8080
spring:
  application:
    name: accounts
  profiles:
    active: local
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8071/
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
    openfeign:
      circuitbreaker:
        enabled: true
    function:
      definition: updateCommunication
    stream:
      bindings:
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
        sendCommunication-out-0:
          destination: send-communication
      kafka:
        binder:
          brokers:
            - localhost:9092
