server:
  port: 8080
spring:
  application:
    name: accounts
  profiles:
    active: local
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8071/
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true